[package]
name = "did_cheqd"
authors.workspace = true
description.workspace = true
license.workspace = true
version = "0.1.0"
edition = "2021"

[lib]
name = "did_cheqd"
path = "src/lib.rs"

[dependencies]
did_resolver = { path = "../../did_resolver" }
tonic = { version = "0.12.3", default-features = false, features = [
    "codegen",
    "prost",
    "channel",
    "tls-native-roots",
] }
prost = { version = "0.13.3", default-features = false }
prost-types = "0.13.3"
async-trait = "0.1.68"
serde_json = "1.0.96"
serde = { version = "1.0.160", features = ["derive"] }
thiserror = "1.0.40"
tokio = { version = "1.38.0" }
chrono = { version = "0.4.24", default-features = false }
url = { version = "2.3.1", default-features = false }

[dev-dependencies]
tokio = { version = "1.38.0", default-features = false, features = [
    "macros",
    "rt",
] }
